name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        echo "upgrading pip"
        sudo $(which python) -m pip install --upgrade pip
        echo "creating ray_installation"
        sudo "mkdir /tmp/ray_installation"
        export PYTHONPATH=/tmp/ray_installation:$PYTHONPATH
        echo "pythonpath: $PYTHONPATH"
        sudo $(which pip) install --prefix="/tmp/ray_installation" ray
        echo "pip freeze before"
        pip freeze
        sudo $(which python) setup.py develop
        echo "pip freeze after"
        pip freeze
    - name: Fix permissions
      run: |
        echo "$PYTHONPATH"
        sudo chmod -R 777 /tmp/ray_installation
    - name: Lint
      run: |
        echo Linter is disabled so far
    - name: Test with pytest and obtain coverage
      run: |
        sudo $(which pip) install pytest
        sudo $(which pip) install pytest-cov
        sudo $(which pytest)
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: ./coverage.xml
#        name: kts-core
